### ISSUE TITLE
UserWarning: Attempted to set unknown attribute "devices" on instance of "Snapshot"

### ISSUE THREAD

**Issue by jdavid** [lxc/pylxd#217]
Hello,

When getting an snapshot many warnings are printed:

    >>> container = client.containers.get(foo)
    >>> container.snapshots.get(bar)
    [...]/pylxd/models/_model.py:113: UserWarning: Attempted to set unknown attribute "devices" on instance of "Snapshot"
      key, self.__class__.__name__
    [...]/pylxd/models/_model.py:113: UserWarning: Attempted to set unknown attribute "architecture" on instance of "Snapshot"
      key, self.__class__.__name__
    [...]/pylxd/models/_model.py:113: UserWarning: Attempted to set unknown attribute "created_at" on instance of "Snapshot"
      key, self.__class__.__name__
    [...]/pylxd/models/_model.py:113: UserWarning: Attempted to set unknown attribute "profiles" on instance of "Snapshot"
      key, self.__class__.__name__
    [...]/pylxd/models/_model.py:113: UserWarning: Attempted to set unknown attribute "expanded_devices" on instance of "Snapshot"
      key, self.__class__.__name__
    [...]/pylxd/models/_model.py:113: UserWarning: Attempted to set unknown attribute "expanded_config" on instance of "Snapshot"
      key, self.__class__.__name__
    [...]/pylxd/models/_model.py:113: UserWarning: Attempted to set unknown attribute "last_used_at" on instance of "Snapshot"
      key, self.__class__.__name__
    [...]/pylxd/models/_model.py:113: UserWarning: Attempted to set unknown attribute "config" on instance of "Snapshot"
      key, self.__class__.__name__
    [...]/pylxd/models/_model.py:113: UserWarning: Attempted to set unknown attribute "ephemeral" on instance of "Snapshot"
      key, self.__class__.__name__

**Comment by ajkavanagh** [comment]
Hi @jdavid - is this still happening ... I'm one of the new maintainers and I'm just planning work around the bugs reported.  Thanks.

**Comment by jdavid** [comment]
Fixed after upgrading to pylxd 2.2.4, thanks!

**Comment by Miso-K** [comment]
Hi, issue is not resolved. I tried pylxd version 2.2.7 and 2.2.8

`>>> c.containers.get('vps1').snapshots.get('test').name
[...]/pylxd/models/_model.py:116: UserWarning: Attempted to set unknown attribute "ephemeral" on instance of "Snapshot"
  key, self.__class__.__name__
[...]/pylxd/models/_model.py:116: UserWarning: Attempted to set unknown attribute "expanded_devices" on instance of "Snapshot"
  key, self.__class__.__name__
[...]/pylxd/models/_model.py:116: UserWarning: Attempted to set unknown attribute "config" on instance of "Snapshot"
  key, self.__class__.__name__
[...]/pylxd/models/_model.py:116: UserWarning: Attempted to set unknown attribute "profiles" on instance of "Snapshot"
  key, self.__class__.__name__
[...]/pylxd/models/_model.py:116: UserWarning: Attempted to set unknown attribute "last_used_at" on instance of "Snapshot"
  key, self.__class__.__name__
[...]/pylxd/models/_model.py:116: UserWarning: Attempted to set unknown attribute "expanded_config" on instance of "Snapshot"
  key, self.__class__.__name__
[...]/pylxd/models/_model.py:116: UserWarning: Attempted to set unknown attribute "devices" on instance of "Snapshot"
  key, self.__class__.__name__
[...]/pylxd/models/_model.py:116: UserWarning: Attempted to set unknown attribute "architecture" on instance of "Snapshot"
  key, self.__class__.__name__
'test'`

**Comment by Miso-K** [comment]
My lxd version is 2.0.11, I know it is old version and I'm going to upgrade it to 3.x.
